### PR TITLE
Removing product directory

### PR DESCRIPTION
**Pull request by Akshaz**

### CODE REVIEW

**Comment by Mihir-Karbelkar** [comment]
Great diff although I would request you to solve one issue with one pull request. Can you update the pull request with the same.

**Comment by Mihir-Karbelkar** [comment]
Maybe you can follow this tutorial https://stackoverflow.com/questions/9790448/how-to-update-a-pull-request-from-forked-repo and if you have any doubts feel free to ask

**Review by Mihir-Karbelkar — COMMENTED** [review]
You should open another pull request as this is a different issue. Although I would suggest you to tackle only one good first issue to get started. We will create more issues which won't be good first issue so maybe you can tackle them next. Cheers! Otherwise Great diff

**Comment by Akshaz** [comment]
Thanks!
According to the tutorial I have updated my pull request which is tackling only one issue which would be removal of the product directory.
I am eagerly waiting for more issues to be solved! 😀

**Comment by Akshaz** [comment]
I was just curious about what will happen if I close my pull request.
Sorry about that!

**Comment by Mihir-Karbelkar** [comment]
> I was just curious about what will happen if I close my pull request.
> Sorry about that!

It's fine. This repo is anyway for learning.

**Comment by Mihir-Karbelkar** [comment]
Now your diff is fine but you are sending in three commits which is not required by this issue. What you should do is keep the commit that removes the product directory and delete the rest and update the pull request. cheers

**Comment by Akshaz** [comment]
I squashed those commits into one.
Is there anything else i should do?

**Comment by Mihir-Karbelkar** [comment]
Congrats on your first PR

**Pull request merged**
